Repository neuronets/nobrainer, pull requests merged in 2021-06, with the labels that each got.

#147 fix: Update release.yml to handle branch protection
  .github/workflows/release.yml
Labels: minor, release

#148 Enh/docker
  README.md
  docker/cpu.Dockerfile
  docker/gpu.Dockerfile
  nobrainer/cli/main.py
Labels: minor, release

#126 ENH: Bayesian neural network architectures with training requisites
  nobrainer/bayesian_utils.py
  nobrainer/layers/groupnorm.py
  nobrainer/models/bayesian-meshnet.py
  nobrainer/models/bayesian_vnet.py
  nobrainer/models/bayesian_vnet_semi.py
  nobrainer/models/tests/models_test.py
  nobrainer/models/vnet.py
Labels: enhancement

#150 fix: change nobrainer models repo, readme, and guide notebooks
  LICENSE
  README.md
  guide/01-getting_started.ipynb
  guide/Inference_with_kwyk_model.ipynb
  guide/train_binary_classification.ipynb
  guide/train_binary_segmentation.ipynb
  guide/train_generation_progressive.ipynb
  guide/train_on_multiple_gpus.ipynb
  guide/transfer_learning.ipynb
Labels: minor, release

#157 fix: replace key retrieval and normalizers
  docker/cpu.Dockerfile
  docker/gpu.Dockerfile
  guide/inference_with_kwyk_model.ipynb
  guide/train_generation_progressive.ipynb
  guide/train_on_multiple_gpus.ipynb
  guide/transfer_learning.ipynb
  nobrainer/prediction.py
Labels: patch, release
